export const ERROR_CODES = {
  // Order
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_ORDER: 'INVALID_ORDER',
  INVALID_ORDER_TRANSITION: 'INVALID_ORDER_TRANSITION',
  // Payment
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  INVALID_PAYMENT_TRANSITION: 'INVALID_PAYMENT_TRANSITION',
  // Inventory
  INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',
  INSUFFICIENT_INVENTORY: 'INSUFFICIENT_INVENTORY',
  INVALID_RESERVATION: 'INVALID_RESERVATION',
  // Shipping
  SHIPMENT_NOT_FOUND: 'SHIPMENT_NOT_FOUND',
  INVALID_SHIPMENT_TRANSITION: 'INVALID_SHIPMENT_TRANSITION',
  // Notification
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_ALREADY_SENT: 'NOTIFICATION_ALREADY_SENT',
  // Workflow
  ORDER_WORKFLOW_NOT_FOUND: 'ORDER_WORKFLOW_NOT_FOUND',
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
